create table script_options (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  script_name TEXT NOT NULL,
  extra_input BOOLEAN NOT NULL,
  description TEXT NOT NULL,
  code TEXT NOT NULL
)