CREATE TABLE script_data(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type TEXT NOT NULL,
    command TEXT NOT NULL,
    duration INTEGER,
    condition TEXT,
    script_relation INTEGER REFERENCES script_titles(id) ON DELETE CASCADE NOT NULL
)